### ISSUE TITLE
Docker Eg: reference-ccda-validator

### ISSUE THREAD

**Issue by wahmedswl** [bitnami/bitnami-docker-tomcat#66]
Hi, need to create docker-compose.yml to deploy https://github.com/siteadmin/reference-ccda-validator
It simply need cfg file copied to ```conf\Catalina\localhost``` and also dir where cfg will reside.

Any help would be appreciated.
Thanks

**Comment by wahmedswl** [comment]
Hi, i have created following Dockerfile
```
FROM bitnami/tomcat:latest
COPY referenceccdaservice.xml /opt/bitnami/tomcat/conf/Catalina/localhost
COPY configuration /opt/ccda_validator/
RUN CCDA_VALIDATOR_WAR=$(curl -s https://api.github.com/repos/siteadmin/reference-ccda-validator/releases/latest | grep browser_download_url | cut -d '"' -f 4) && curl -o /opt/bitnami/tomcat/webapps/referenceccdaservice.war $CCDA_VALIDATOR_WAR
```
But, on run referenceccdaservice.war is not getting deployed, following is the output of the container run
```
11-Jul-2017 17:48:16.822 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
11-Jul-2017 17:48:16.822 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.awt.headless=true
11-Jul-2017 17:48:16.822 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -XX:+UseG1GC
11-Jul-2017 17:48:16.823 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dfile.encoding=UTF-8
11-Jul-2017 17:48:16.823 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djdk.tls.ephemeralDHKeySize=2048
11-Jul-2017 17:48:16.823 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.protocol.handler.pkgs=org.apache.catalina.webresources
11-Jul-2017 17:48:16.823 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.base=/opt/bitnami/tomcat
11-Jul-2017 17:48:16.823 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.home=/opt/bitnami/tomcat
11-Jul-2017 17:48:16.823 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.io.tmpdir=/opt/bitnami/tomcat/temp
11-Jul-2017 17:48:16.823 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: [/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib]
11-Jul-2017 17:48:17.093 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-nio-8080"]
11-Jul-2017 17:48:17.130 INFO [main] org.apache.tomcat.util.net.NioSelectorPool.getSharedSelector Using a shared selector for servlet write/read
11-Jul-2017 17:48:17.136 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["ajp-nio-8009"]
11-Jul-2017 17:48:17.145 INFO [main] org.apache.tomcat.util.net.NioSelectorPool.getSharedSelector Using a shared selector for servlet write/read
11-Jul-2017 17:48:17.147 INFO [main] org.apache.catalina.startup.Catalina.load Initialization processed in 887 ms
11-Jul-2017 17:48:17.222 INFO [main] org.apache.catalina.core.StandardService.startInternal Starting service [Catalina]
11-Jul-2017 17:48:17.222 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet Engine: Apache Tomcat/9.0.0.M22
11-Jul-2017 17:48:17.234 SEVERE [main] org.apache.catalina.startup.HostConfig.beforeStart Unable to create directory for deployment: [/bitnami/tomcat/conf/Catalina/localhost]
11-Jul-2017 17:48:17.265 INFO [main] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive [/bitnami/tomcat/data/referenceccdaservice.war]
11-Jul-2017 17:48:17.332 SEVERE [main] org.apache.catalina.startup.ContextConfig.beforeStart Exception fixing docBase for context [/referenceccdaservice]
 java.util.zip.ZipException: error in opening zip file
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(ZipFile.java:219)
        at java.util.zip.ZipFile.<init>(ZipFile.java:149)
        at java.util.jar.JarFile.<init>(JarFile.java:166)
        at java.util.jar.JarFile.<init>(JarFile.java:103)
        at sun.net.www.protocol.jar.URLJarFile.<init>(URLJarFile.java:93)
        at sun.net.www.protocol.jar.URLJarFile.getJarFile(URLJarFile.java:69)
        at sun.net.www.protocol.jar.JarFileFactory.get(JarFileFactory.java:99)
        at sun.net.www.protocol.jar.JarURLConnection.connect(JarURLConnection.java:122)
        at sun.net.www.protocol.jar.JarURLConnection.getJarFile(JarURLConnection.java:89)
        at org.apache.catalina.startup.ExpandWar.expand(ExpandWar.java:130)
        at org.apache.catalina.startup.ContextConfig.fixDocBase(ContextConfig.java:615)
        at org.apache.catalina.startup.ContextConfig.beforeStart(ContextConfig.java:748)
        at org.apache.catalina.startup.ContextConfig.lifecycleEvent(ContextConfig.java:301)
        at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
        at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:424)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:182)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:740)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:716)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:703)
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:978)
        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1850)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
        at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
        at org.apache.catalina.startup.HostConfig.deployWARs(HostConfig.java:762)
        at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:431)
        at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1578)
        at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:308)
        at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
        at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:424)
        at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:367)
        at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:964)
        at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:839)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1425)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1415)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
        at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134)
        at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:941)
        at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:258)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.core.StandardService.startInternal(StandardService.java:422)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:770)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.startup.Catalina.start(Catalina.java:657)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:355)
        at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:495)

11-Jul-2017 17:48:17.379 SEVERE [main] org.apache.catalina.core.ContainerBase.addChildInternal ContainerBase.addChild: start:
 org.apache.catalina.LifecycleException: Failed to initialize component [org.apache.catalina.webresources.WarResourceSet@27a8c74e]
        at org.apache.catalina.util.LifecycleBase.handleSubClassException(LifecycleBase.java:441)
        at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:139)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:173)
        at org.apache.catalina.webresources.StandardRoot.startInternal(StandardRoot.java:699)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.core.StandardContext.resourcesStart(StandardContext.java:4748)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:4880)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:740)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:716)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:703)
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:978)
        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1850)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
        at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
        at org.apache.catalina.startup.HostConfig.deployWARs(HostConfig.java:762)
        at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:431)
        at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1578)
        at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:308)
        at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
        at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:424)
        at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:367)
        at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:964)
        at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:839)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1425)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1415)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
        at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134)
        at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:941)
        at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:258)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.core.StandardService.startInternal(StandardService.java:422)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:770)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.startup.Catalina.start(Catalina.java:657)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:355)
        at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:495)
Caused by: java.lang.IllegalArgumentException: java.util.zip.ZipException: error in opening zip file
        at org.apache.catalina.webresources.AbstractSingleArchiveResourceSet.initInternal(AbstractSingleArchiveResourceSet.java:113)
        at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:136)
        ... 44 more
Caused by: java.util.zip.ZipException: error in opening zip file
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(ZipFile.java:219)
        at java.util.zip.ZipFile.<init>(ZipFile.java:149)
        at java.util.jar.JarFile.<init>(JarFile.java:166)
        at java.util.jar.JarFile.<init>(JarFile.java:103)
        at org.apache.catalina.webresources.AbstractSingleArchiveResourceSet.initInternal(AbstractSingleArchiveResourceSet.java:110)
        ... 45 more

11-Jul-2017 17:48:17.380 SEVERE [main] org.apache.catalina.startup.HostConfig.deployWAR Error deploying web application archive [/bitnami/tomcat/data/referenceccdaservice.war]
 java.lang.IllegalStateException: ContainerBase.addChild: start: org.apache.catalina.LifecycleException: Failed to initialize component [org.apache.catalina.webresources.WarResourceSet@27a8c74e]
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:744)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:716)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:703)
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:978)
        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1850)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
        at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
        at org.apache.catalina.startup.HostConfig.deployWARs(HostConfig.java:762)
        at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:431)
        at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1578)
        at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:308)
        at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
        at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:424)
        at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:367)
        at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:964)
        at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:839)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1425)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1415)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
        at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134)
        at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:941)
        at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:258)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.core.StandardService.startInternal(StandardService.java:422)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:770)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.startup.Catalina.start(Catalina.java:657)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:355)
        at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:495)

11-Jul-2017 17:48:17.388 INFO [main] org.apache.catalina.startup.HostConfig.deployWAR Deployment of web application archive [/bitnami/tomcat/data/referenceccdaservice.war] has finished in [115] ms
11-Jul-2017 17:48:17.395 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/bitnami/tomcat/data/manager]
11-Jul-2017 17:48:17.804 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/bitnami/tomcat/data/manager] has finished in [409] ms
11-Jul-2017 17:48:17.805 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/bitnami/tomcat/data/docs]
11-Jul-2017 17:48:17.832 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/bitnami/tomcat/data/docs] has finished in [27] ms
11-Jul-2017 17:48:17.833 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/bitnami/tomcat/data/ROOT]
11-Jul-2017 17:48:17.854 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/bitnami/tomcat/data/ROOT] has finished in [20] ms
11-Jul-2017 17:48:17.854 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/bitnami/tomcat/data/host-manager]
11-Jul-2017 17:48:17.879 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/bitnami/tomcat/data/host-manager] has finished in [25] ms
11-Jul-2017 17:48:17.880 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/bitnami/tomcat/data/examples]
11-Jul-2017 17:48:18.478 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/bitnami/tomcat/data/examples] has finished in [599] ms
11-Jul-2017 17:48:18.487 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8080"]
11-Jul-2017 17:48:18.518 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["ajp-nio-8009"]
11-Jul-2017 17:48:18.527 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in 1379 ms
```

Any help would be appreciated, Thanks

**Comment by javsalgar** [comment]
Thanks for reporting. I think that there may be an error with the downloaded war file. Could you check that the content is actually a war file and not a 404 HTML page? Another way to test it could be to manually download the war and adding it with a COPY command in the Dockerfile. That would ensure that no download errors occurred.

**Comment by wahmedswl** [comment]
@javsalgar you are right, ```referenceccdaservice.war``` was html. It was due to redirect which now I have fixed but ```referenceccdaservice.war``` is not being copied.
I have modified the commands it now
```
RUN CCDA_VALIDATOR_WAR=$(curl -s https://api.github.com/repos/siteadmin/reference-ccda-validator/releases/latest | grep browser_download_url | cut -d '"' -f 4) && (curl -o referenceccdaservice.war $CCDA_VALIDATOR_WAR -L)
```
The file is now downloaded as it hinted in the docker build output
```
Build an image from a Dockerfile
PS E:\Quicks\docker> docker build -t ccda_validator .
Sending build context to Docker daemon   44.8MB
Step 1/4 : FROM bitnami/tomcat:latest
 ---> 3bf5a1063789
Step 2/4 : COPY referenceccdaservice.xml /opt/bitnami/tomcat/conf/Catalina/localhost
 ---> aee732748399
Removing intermediate container cce794680e91
Step 3/4 : COPY configuration /opt/ccda_validator/
 ---> 3fbca2cb79d8
Removing intermediate container e9342f2a5903
Step 4/4 : RUN CCDA_VALIDATOR_WAR=$(curl -s https://api.github.com/repos/siteadmin/reference-ccda-validator/releases/latest | grep browser_download_url | cut -d '"' -f 4) && (curl -o referenceccdaservice.war $CCDA_VALIDATOR_WAR -L)
 ---> Running in 6813cca66169
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   614    0   614    0     0    482      0 --:--:--  0:00:01 --:--:--   481
100 42.5M  100 42.5M    0     0   197k      0  0:03:41  0:03:41 --:--:--  356k
 ---> ff71098f5134
Removing intermediate container 6813cca66169
Successfully built ff71098f5134
Successfully tagged ccda_validator:latest
SECURITY WARNING: You are building a Docker image from Windows against a non-Windows Docker host. All files and directories added to build context will have '-rwxr-xr-x' permissions. It is recommended to double check and reset permissions for sensitive files and director
ies.
```
