### ISSUE TITLE
Can not start with persistence volume

### ISSUE THREAD

**Issue by unomind** [bitnami/bitnami-docker-tomcat#73]
docker-compose.yml
```yaml
version: '2'

services:
  tomcat:
    image: 'bitnami/tomcat:latest'
    ports:
      - '10023:8080'
    environment:
      - TOMCAT_USERNAME=user
      - TOMCAT_PASSWORD=pass
      - TOMCAT_ALLOW_REMOTE_MANAGEMENT=1
    volumes:
      - ./bitnami:/bitnami

```

`docker-compose up` log:
```
bitnami-tomcat docker-compose up        
Starting bitnami-tomcat_tomcat_1 ... done
Attaching to bitnami-tomcat_tomcat_1
tomcat_1  | 
tomcat_1  | Welcome to the Bitnami tomcat container
tomcat_1  | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-tomcat
tomcat_1  | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-tomcat/issues
tomcat_1  | 
tomcat_1  | nami    INFO  Initializing tomcat
tomcat_1  | Error executing 'postInstallation': ELOOP: too many symbolic links encountered, stat '/bitnami/tomcat/data'
bitnami-tomcat_tomcat_1 exited with code 1
```
docker version
```
Client:
 Version:           18.09.2-ce
 API version:       1.39
 Go version:        go1.11.5
 Git commit:        62479626f2
 Built:             Mon Feb 11 23:58:17 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.2-ce
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.11.5
  Git commit:       62479626f2
  Built:            Mon Feb 11 23:55:58 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```
docker-compose version:
```
docker-compose version 1.23.2, build unknown
docker-py version: 3.7.0
CPython version: 3.7.2
OpenSSL version: OpenSSL 1.1.1a  20 Nov 2018
```
Host OS and kernel:
```
Linux 4.19.23-1-MANJARO 
```

Any help?
Thanks

**Comment by juan131** [comment]
Hi @unomind 

I was unable to reproduce the issue using the same `docker-compose.yml` you shared. See the logs:

```
$ mkdir bitnami
$ docker-compose up
...
tomcat_1  |
tomcat_1  | Welcome to the Bitnami tomcat container
tomcat_1  | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-tomcat
tomcat_1  | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-tomcat/issues
tomcat_1  |
tomcat_1  | nami    INFO  Initializing tomcat
tomcat_1  | tomcat  INFO  Enabling remote connections for manager and host-manager applications...
tomcat_1  | tomcat  INFO
tomcat_1  | tomcat  INFO  ########################################################################
tomcat_1  | tomcat  INFO   Installation parameters for tomcat:
tomcat_1  | tomcat  INFO     Username: user
tomcat_1  | tomcat  INFO     Password: **********
tomcat_1  | tomcat  INFO   (Passwords are not shown for security reasons)
tomcat_1  | tomcat  INFO  ########################################################################
tomcat_1  | tomcat  INFO
tomcat_1  | nami    INFO  tomcat successfully initialized
tomcat_1  | INFO  ==> Starting tomcat...
```

Do you have any content from previous deployment in your `./bitnami` directory (the one you're mounting)?

**Comment by unomind** [comment]
@juan131 , my `./bitnami` is an empty directory

**Comment by juan131** [comment]
What version of `bitnami/tomcat` image are you using? Could you ensure to use the latest one by running:

```
$ docker pull bitnami/tomcat:latest
```

Could you add the env. variable below so we can obtain more info in the logs? Then share the logs please

```
      ...    
      environment:
      - NAMI_DEBUG='--log-level=trace'
```

**Comment by unomind** [comment]
from my `docker-compose.yml` above, i'm sure that i use the latest version of  `bitnami/tomcat`

**Comment by juan131** [comment]
Hi @unomind 

Thanks for the info. Could you share the logs obtained when adding the env. variable `NAMI_DEBUG`, as suggested in my last comment?

**Comment by unomind** [comment]
Here the log with `NAMI_DEBUG`:
```
Starting bitnami-tomcat_tomcat_1 ... done
Attaching to bitnami-tomcat_tomcat_1
tomcat_1  | app-entrypoint.sh 09:07:14.67 
tomcat_1  | app-entrypoint.sh 09:07:14.67 Welcome to the Bitnami tomcat container
tomcat_1  | app-entrypoint.sh 09:07:14.67 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-tomcat
tomcat_1  | app-entrypoint.sh 09:07:14.68 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-tomcat/issues
tomcat_1  | app-entrypoint.sh 09:07:14.68 
tomcat_1  | nami    INFO  Initializing tomcat
tomcat_1  | tomcat  TRACE [prepareDataToPersist] Preparing /opt/bitnami/tomcat/conf to persist in /bitnami/tomcat/conf
tomcat_1  | Error executing 'postInstallation': EACCES: permission denied, mkdir '/bitnami/tomcat'
tomcat_1  | nami    TRACE Error: Error executing 'postInstallation': EACCES: permission denied, mkdir '/bitnami/tomcat'
tomcat_1  |     at Object.fs.mkdirSync (fs.js:885:18)
tomcat_1  |     at mkdirsSync (/opt/bitnami/nami/node_modules/nami-utils/node_modules/fs-extra/lib/mkdirs/mkdirs-sync.js:29:9)
tomcat_1  |     at Object.mkdirsSync (/opt/bitnami/nami/node_modules/nami-utils/node_modules/fs-extra/lib/mkdirs/mkdirs-sync.js:35:16)
tomcat_1  |     at Object.mkdir (/opt/bitnami/nami/node_modules/nami-utils/lib/file/mkdir.js:28:8)
tomcat_1  |     at Object.wrappedFn (/opt/bitnami/nami/node_modules/nami-utils/lib/function-wrapping.js:191:17)
tomcat_1  |     at _recursiveMove (/.nami/components/com.bitnami.tomcat/lib/volume.js:37:13)
tomcat_1  |     at _.each (/.nami/components/com.bitnami.tomcat/lib/volume.js:131:7)
tomcat_1  |     at r (/opt/bitnami/nami/node_modules/lodash/index.js:5:348)
tomcat_1  |     at Function.sf (/opt/bitnami/nami/node_modules/lodash/index.js:78:256)
tomcat_1  |     at Function.<anonymous> (/opt/bitnami/nami/node_modules/lodash/index.js:51:276)
bitnami-tomcat_tomcat_1 exited with code 1
```

**Comment by juan131** [comment]
As you can see in the error below:

```bash
tomcat_1  | Error executing 'postInstallation': EACCES: permission denied, mkdir '/bitnami/tomcat'
```

It seems you're facing a permissions issue. Tomcat uses a "non-root" approach (see https://github.com/bitnami/bitnami-docker-tomcat#why-use-a-non-root-container and https://github.com/bitnami/bitnami-docker-tomcat#9013-r27--8535-r26-8053-r131--7092-r20) and the volume you're mounting doesn't have the right privileges so the "non-root" user can write on it.

Could you ensure you give writing permissions (775) to the `./bitnami` directory you're using as a volume?

**Comment by unomind** [comment]
Thank you @juamedgod .
I've chage the dir permission as you suggested.
```
drwxrwxr-x 3 root      root      4096 Mar  1 09:55 bitnami
-rw-r--r-- 1 sumarsono sumarsono  303 Feb 28 16:06 docker-compose.yml
```

And when i fire up `docker compose up`:
```
Starting bitnami-tomcat_tomcat_1 ... done
Attaching to bitnami-tomcat_tomcat_1
tomcat_1  | app-entrypoint.sh 02:55:02.33 
tomcat_1  | app-entrypoint.sh 02:55:02.34 Welcome to the Bitnami tomcat container
tomcat_1  | app-entrypoint.sh 02:55:02.34 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-tomcat
tomcat_1  | app-entrypoint.sh 02:55:02.34 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-tomcat/issues
tomcat_1  | app-entrypoint.sh 02:55:02.34 
tomcat_1  | nami    INFO  Initializing tomcat
tomcat_1  | tomcat  TRACE [prepareDataToPersist] Preparing /opt/bitnami/tomcat/conf to persist in /bitnami/tomcat/conf
tomcat_1  | tomcat  TRACE [prepareDataToPersist] Preparing /opt/bitnami/tomcat/data to persist in /bitnami/tomcat/data
tomcat_1  | tomcat  TRACE [retry] Trying to configure permissions... 19 remaining attempts
tomcat_1  | tomcat  TRACE [retry] Trying to configure permissions... 18 remaining attempts
tomcat_1  | tomcat  TRACE [retry] Trying to configure permissions... 17 remaining attempts
tomcat_1  | tomcat  TRACE [retry] Trying to configure permissions... 16 remaining attempts
tomcat_1  | tomcat  TRACE [retry] Trying to configure permissions... 15 remaining attempts
tomcat_1  | tomcat  TRACE [retry] Trying to configure permissions... 14 remaining attempts
tomcat_1  | tomcat  TRACE [retry] Trying to configure permissions... 13 remaining attempts
tomcat_1  | tomcat  TRACE [retry] Trying to configure permissions... 12 remaining attempts
tomcat_1  | tomcat  TRACE [retry] Trying to configure permissions... 11 remaining attempts
tomcat_1  | tomcat  TRACE [retry] Trying to configure permissions... 10 remaining attempts
tomcat_1  | tomcat  TRACE [retry] Trying to configure permissions... 9 remaining attempts
tomcat_1  | tomcat  TRACE [retry] Trying to configure permissions... 8 remaining attempts
tomcat_1  | tomcat  TRACE [retry] Trying to configure permissions... 7 remaining attempts
tomcat_1  | tomcat  TRACE [retry] Trying to configure permissions... 6 remaining attempts
tomcat_1  | tomcat  TRACE [retry] Trying to configure permissions... 5 remaining attempts
tomcat_1  | tomcat  TRACE [retry] Trying to configure permissions... 4 remaining attempts
tomcat_1  | tomcat  TRACE [retry] Trying to configure permissions... 3 remaining attempts
tomcat_1  | tomcat  TRACE [retry] Trying to configure permissions... 2 remaining attempts
tomcat_1  | tomcat  TRACE [retry] Trying to configure permissions... 1 remaining attempts
tomcat_1  | tomcat  TRACE [retry] Trying to configure permissions... 0 remaining attempts
tomcat_1  | Error executing 'postInstallation': ELOOP: too many symbolic links encountered, stat '/bitnami/tomcat/data'
tomcat_1  | nami    TRACE Error: Error executing 'postInstallation': ELOOP: too many symbolic links encountered, stat '/bitnami/tomcat/data'
tomcat_1  |     at Object.fs.statSync (fs.js:948:11)
tomcat_1  |     at isBrokenLink (/.nami/components/com.bitnami.tomcat/lib/component.js:151:14)
tomcat_1  |     at _configurePermissions (/.nami/components/com.bitnami.tomcat/lib/component.js:165:12)
tomcat_1  |     at utilsFunctions.retry (/.nami/components/com.bitnami.tomcat/lib/component.js:208:13)
tomcat_1  |     at Object.retry (/.nami/components/com.bitnami.tomcat/lib/utils.js:28:14)
tomcat_1  |     at _.each (/.nami/components/com.bitnami.tomcat/lib/component.js:200:24)
tomcat_1  |     at r (/opt/bitnami/nami/node_modules/lodash/index.js:5:348)
tomcat_1  |     at Function.sf (/opt/bitnami/nami/node_modules/lodash/index.js:78:256)
tomcat_1  |     at Function.<anonymous> (/opt/bitnami/nami/node_modules/lodash/index.js:51:276)
tomcat_1  |     at Object.configurePermissions (/.nami/components/com.bitnami.tomcat/lib/component.js:179:7)
bitnami-tomcat_tomcat_1 exited with code 1
```

**Comment by juan131** [comment]
Could you try the workaround below in the `docker-compose.yml`? Indicate the absolute path to your **bitnami** directory (please note that you need to substitute the placeholder  /ABSOLUTE/PATH/TO with the actual absolute path):

```diff
-    volumes:
-      - ./bitnami:/bitnami
+    volumes:
+      - /ABSOLUTE/PATH/TO/bitnami:/bitnami
```

**Comment by unomind** [comment]
I tried with this conf.
```
volumes:
      - /home/sumarsono/Sumarsono/sumar-docker/bitnami-tomcat/bitnami:/bitnami
```
Here the log:
```
➜  bitnami-tomcat docker-compose up
Creating network "bitnami-tomcat_default" with the default driver
Creating bitnami-tomcat_tomcat_1 ... done
Attaching to bitnami-tomcat_tomcat_1
tomcat_1  | app-entrypoint.sh 08:36:37.81 
tomcat_1  | app-entrypoint.sh 08:36:37.82 Welcome to the Bitnami tomcat container
tomcat_1  | app-entrypoint.sh 08:36:37.82 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-tomcat
tomcat_1  | app-entrypoint.sh 08:36:37.82 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-tomcat/issues
tomcat_1  | app-entrypoint.sh 08:36:37.82 
tomcat_1  | nami    INFO  Initializing tomcat
tomcat_1  | tomcat  TRACE [restorePersistedData] Restoring /bitnami/tomcat/conf to /opt/bitnami/tomcat/conf
tomcat_1  | tomcat  TRACE [restorePersistedData] Restoring /bitnami/tomcat/data to /opt/bitnami/tomcat/data
tomcat_1  | tomcat  TRACE [retry] Trying to configure permissions... 19 remaining attempts
tomcat_1  | tomcat  TRACE [retry] Trying to configure permissions... 18 remaining attempts
tomcat_1  | tomcat  TRACE [retry] Trying to configure permissions... 17 remaining attempts
tomcat_1  | tomcat  TRACE [retry] Trying to configure permissions... 16 remaining attempts
tomcat_1  | tomcat  TRACE [retry] Trying to configure permissions... 15 remaining attempts
tomcat_1  | tomcat  TRACE [retry] Trying to configure permissions... 14 remaining attempts
tomcat_1  | tomcat  TRACE [retry] Trying to configure permissions... 13 remaining attempts
tomcat_1  | tomcat  TRACE [retry] Trying to configure permissions... 12 remaining attempts
tomcat_1  | tomcat  TRACE [retry] Trying to configure permissions... 11 remaining attempts
tomcat_1  | tomcat  TRACE [retry] Trying to configure permissions... 10 remaining attempts
tomcat_1  | tomcat  TRACE [retry] Trying to configure permissions... 9 remaining attempts
tomcat_1  | tomcat  TRACE [retry] Trying to configure permissions... 8 remaining attempts
tomcat_1  | tomcat  TRACE [retry] Trying to configure permissions... 7 remaining attempts
tomcat_1  | tomcat  TRACE [retry] Trying to configure permissions... 6 remaining attempts
tomcat_1  | tomcat  TRACE [retry] Trying to configure permissions... 5 remaining attempts
tomcat_1  | tomcat  TRACE [retry] Trying to configure permissions... 4 remaining attempts
tomcat_1  | tomcat  TRACE [retry] Trying to configure permissions... 3 remaining attempts
tomcat_1  | tomcat  TRACE [retry] Trying to configure permissions... 2 remaining attempts
tomcat_1  | tomcat  TRACE [retry] Trying to configure permissions... 1 remaining attempts
tomcat_1  | tomcat  TRACE [retry] Trying to configure permissions... 0 remaining attempts
tomcat_1  | Error executing 'postInstallation': ELOOP: too many symbolic links encountered, stat '/bitnami/tomcat/data'
tomcat_1  | nami    TRACE Error: Error executing 'postInstallation': ELOOP: too many symbolic links encountered, stat '/bitnami/tomcat/data'
tomcat_1  |     at Object.fs.statSync (fs.js:948:11)
tomcat_1  |     at isBrokenLink (/.nami/components/com.bitnami.tomcat/lib/component.js:151:14)
tomcat_1  |     at _configurePermissions (/.nami/components/com.bitnami.tomcat/lib/component.js:165:12)
tomcat_1  |     at utilsFunctions.retry (/.nami/components/com.bitnami.tomcat/lib/component.js:208:13)
tomcat_1  |     at Object.retry (/.nami/components/com.bitnami.tomcat/lib/utils.js:28:14)
tomcat_1  |     at _.each (/.nami/components/com.bitnami.tomcat/lib/component.js:200:24)
tomcat_1  |     at r (/opt/bitnami/nami/node_modules/lodash/index.js:5:348)
tomcat_1  |     at Function.sf (/opt/bitnami/nami/node_modules/lodash/index.js:78:256)
tomcat_1  |     at Function.<anonymous> (/opt/bitnami/nami/node_modules/lodash/index.js:51:276)
tomcat_1  |     at Object.configurePermissions (/.nami/components/com.bitnami.tomcat/lib/component.js:179:7)
```

**Comment by unomind** [comment]
I've fix this by modify my volumes configuration, like this. I don't know why. But this fix my issue for now:
```
version: '2'

services:
  tomcat:
    image: 'bitnami/tomcat:latest'
    ports:
      - '10023:8080'
    environment:
      - NAMI_DEBUG='--log-level=trace'
      - TOMCAT_USERNAME=myuname
      - TOMCAT_PASSWORD=mypasswd
      - TOMCAT_ALLOW_REMOTE_MANAGEMENT=1
    volumes:
      - ./conf:/bitnami/tomcat/conf
      - ./app:/bitnami/tomcat/data
```

**Comment by nomisbeme** [comment]
Which filesystem and fs options are in use for the device that provides 
/home/sumarsono/Sumarsono/sumar-docker/bitnami-tomcat/bitnami?

**Comment by unomind** [comment]
@nomisbeme 
```
ext4    defaults,noatime,discard 0 1
```

**Comment by carrodher** [comment]
Hi @unomind, as @juan131 suggested you need to change the permissions in your local folder. During the image build process, we are already creating the `/bitnami` folder and also configuring the permissions for the `root` group. (If you start the container with a non-existent user, like `1001`, it will belong to the **`root` group**).
You can still use local volumes for tomcat, but you need to change the permissions of your local folder before starting the docker-compose.
The above is necessary because tomcat is a non-root image. You can get more info about how to work with non-root containers and why they are important in these links:

- https://docs.bitnami.com/containers/how-to/work-with-non-root-containers/
- https://engineering.bitnami.com/articles/why-non-root-containers-are-important-for-security.html

In the other hand, taking a look at the logs:
- When you was facing the issue:
```bash
...
tomcat_1  | tomcat  TRACE [restorePersistedData] Restoring /bitnami/tomcat/conf to /opt/bitnami/tomcat/conf
tomcat_1  | tomcat  TRACE [restorePersistedData] Restoring /bitnami/tomcat/data to /opt/bitnami/tomcat/data
tomcat_1  | tomcat  TRACE [retry] Trying to configure permissions... 19 remaining attempts
...
```
- Last time without issue:
```bash
...
tomcat_1  | tomcat  TRACE [prepareDataToPersist] Preparing /opt/bitnami/tomcat/conf to persist in /bitnami/tomcat/conf
tomcat_1  | tomcat  TRACE [prepareDataToPersist] Preparing /opt/bitnami/tomcat/data to persist in /bitnami/tomcat/data
...
```

It seems similar but the first one is trying to restore persisted data (`/bitnami/tomcat/conf` and `/bitnami/tomcat/data`) while the second one is preparing the data to be persisted in the future. That means that the first time `/bitnami` folder could include a `.initialized` file from a previous inconsistent deploy or something similar.

You should be able to use the first apporach
```yaml
volumes:
    - /ABSOLUTE/PATH/TO/bitnami:/bitnami
```
taking into account the permission stuff commented above and that `/bitnami` folder doesn't contain any `.initialized` file, also if you can delete the data, you can use `docker-compose down -v`.
